version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/opt
    ports:
      - 80:80
    depends_on:
      - backend

  #redis:
  #  image: redis
  #  ports:
  #    - 6379:6379

  mysql:
    image: mysql:5.7
    environment:
     - MYSQL_DATABASE=nft_new_top
     - MYSQL_ROOT_PASSWORD=0Dhy&WRdgRHk
     - MYSQL_USER=project_api
     - MYSQL_PASSWORD=hy&rDgRHk
     #- MYSQL_ROOT_HOST='%'
    volumes:
     - ./mysql/conf.d:/etc/mysql/conf.d
     - ./mysql/data:/var/lib/mysql
    ports:
     - "13306:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  #postgres:
  #  image: postgres:12
  #  restart: always
  #  environment:
  #    POSTGRES_USER: postgres
  #    POSTGRES_PASSWORD: password
  #  ports:
  #    - '5432:5432'
  #  volumes:
  #    - db-data:/var/lib/postgresql/data:cached

  #worker:
  #  build:
  #    context: backend
  #    dockerfile: Dockerfile
  #  command: celery --app app.tasks worker --loglevel=DEBUG -Q main-queue -c 1

  #flower:  
  #  image: mher/flower
  #  command: celery flower --broker=redis://redis:6379/0 --port=5555
  #  ports:  
  #      - 5555:5555
  #  depends_on:
  #    - "redis"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'mysql+pymysql://project_api:hy&rDgRHk@mysql:3306/nft_new_top?charset=utf8mb4'
    links:
      - mysql
    depends_on:
      - "mysql"

  #frontend:
  #  build:
  #    context: frontend
  #    dockerfile: Dockerfile
  #  stdin_open: true
  #  volumes:
  #    - './frontend:/app:cached'
  #    - './frontend/node_modules:/app/node_modules:cached'
  #  environment:
  #    - NODE_ENV=development


  #volumes:
  #  db-data:
  #
